# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='media/attach/'),
        ),
    ]
